ingressnameOverride: ingress-f5-chart-test31

service:
  serviceName: nginx-rancher-opa
  port: 80

ingress:
  enabled: true
  annotations:
    virtualserverip: 172.16.1.120
    virtualserverhttpport: "81"
    partition: k9s
    balance: round-robin
  hosts:
    - host: f5-ingress-example-31.test
      paths:
        path: /web
